#locators for register
url = https://flights.qedgetech.com/
ObjReg = //a[normalize-space()='Register']
Objname = //input[@id='name']
Objcontact = //input[@id='contact']
ObjEmail = //input[@id='email']
Objpass = //input[@id='address']
Objgender =//select[@name='gender']
Objdob = //input[@id='popupDatepicker']
Objcheckbox = //input[@id='flexCheckChecked']
Objregister = //input[@name='submit']
#Testdata for register
EnterName = selinium
Entercontact =126578
Enterpass = Test456
EnterEmail=abc@gmail.com
EnterGender = M
Enterdob = 18-11-2010